# Generated by Django 4.2.2 on 2023-07-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
    ]
